# Generated by Django 4.0.5 on 2022-06-05 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_teacher_degree'),
        ('college', '0003_remove_grade_lesson_grade_timetable_course_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ('date', 'start_at'), 'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписание'},
        ),
        migrations.AlterField(
            model_name='timetable',
            name='auditorium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable', to='college.auditorium', verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timetable', to='college.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable', to='college.lesson', verbose_name='Занятие'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable', to='users.teacher', verbose_name='Преподаватель'),
        ),
    ]
