# Generated by Django 4.0.5 on 2022-06-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='degree',
            field=models.CharField(choices=[('bachelor', 'Бакалавр'), ('master', 'Магистр'), ('candidate', 'Доцент'), ('doctor', 'Профессор')], max_length=16, verbose_name='Категория'),
        ),
    ]
