# Generated by Django 4.0.5 on 2022-06-04 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_teacher_degree'),
        ('college', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='lesson',
        ),
        migrations.AddField(
            model_name='grade',
            name='timetable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='college.timetable', verbose_name='Занятие'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название курса')),
                ('students', models.ManyToManyField(related_name='courses', to='users.student')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.AddField(
            model_name='timetable',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timetables', to='college.course', verbose_name='Курс'),
        ),
    ]
